### ISSUE TITLE
Python3 compilation

### ISSUE THREAD

**Issue by rodrigob** [classner/fertilized-forests#24]
I am not that familiar with scons. What is the recommend approach to compile for python3 (instead of python2.7) ?

**Comment by ChrislS** [comment]
Hi Rodrigo!
Currently, the library only works with Python 2.7. I will have a look at the steps necessary to make it compatible with Python 3 in the afternoon and come back to you on this. Maybe it's a quick thing and can be done immediately.

**Comment by rodrigob** [comment]
Thanks. Looking forward for guidelines.

**Comment by ChrislS** [comment]
So, I checked and it shouldn't be hard to port the library methods. Unfortunately, SCons does not yet support Python 3:

    scons: *** SCons does not run under Python version 3.3.5.
    Python 3 and above are not yet supported.

However, it should soon: "[...] as we are moving toward supporting Python 3." (http://www.scons.org/RELEASE.txt). I'm not touching the build system right now, but will have a look at the issue again when SCons moved forward or I switched to CMake / [biicode](https://www.biicode.com/).

Could you confirm that issue #23 is not occurring with `unstable`? I'll merge `unstable` to `master` today and fix it to 1.01.

**Comment by rodrigob** [comment]
But cannot scons run with python2 to compile projects using python3 ?

Seems like two different issues (running scons with python3, versus compiling projects which use python3)...

**Comment by ChrislS** [comment]
Sure, this is possible. However, I used the synergies to have a Python build system build a Python extension library and use `sys.executable` and the facilities to locate the numpy headers, etc. of the executing Python to link against its libraries.

It's possible to remove this code and introduce a new parameter to the python installation, but then the build system has to undergo some testing again, for which I currently just don't have the time (two submissions this week).

This is why I'd suggest to use Python 2.7 for the moment and upgrade build and library compatibility in one go.

**Comment by rodrigob** [comment]
Sure I understand.
Using python 2.7 is not an option, since I wanted to integrate pyfertilized in an existing python3 code base. I will just wait patiently in the mean time... Good luck with the submissions !

**Comment by ChrislS** [comment]
Ok, I'll leave this issue open and repost when there are news concerning Python 3.

Just in case: if you could confirm #23 in `unstable`, I could still include changes in v1.01.

**Comment by codegrafix** [comment]
Any news? I have the same problem!

**Comment by classner** [comment]
Is going to be solved in a few days. I'm working on a CMake build system, making build and implementation independent, and making the code compatible to Python3. I'll update this issue...

**Comment by codegrafix** [comment]
great news. big thanks in advance!

**Comment by classner** [comment]
Hi Rodrigo, hi Patrick,

this is solved, finally! I did a major redesign of the build system as announced, and the library is now built using CMake. This should make many things a lot simpler, and decouples build and runtime completely.

Additionally, I made the necessary transitions to have the code work with Python 3, so you should be all set now! I keep the changes on `unstable` for a few more days to have it in production use, but the CI builds on Linux, Mac OS and Windows are all passing and it should be running smoothly already. Let me know what you think, and, of course, if you encounter any issues!

Best,
Christoph

**Comment by classner** [comment]
Closing as implemented.
