### ISSUE TITLE
boost python

### ISSUE THREAD

**Issue by burtontimothy** [classner/fertilized-forests#28]
I installed boost 1.58.0 using brew (on a Mac) and get the following error when running cmake: 

--------

Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/local/include

  Could not find the following Boost libraries

          boost_python

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.

--------

I don't have a boost_python directory in my boost installation, but I do have a python directory. Could this be an issue version with boost?

**Comment by classner** [comment]
Hi Timothy!

To install boost python, you need to take some additional steps for the brew installation (e.g., see [here](http://www.pyimagesearch.com/2015/04/27/installing-boost-and-boost-python-on-osx-with-homebrew/) for further explanation and tutorial). Could this be the source of the problem?

Best,
Christoph

**Comment by classner** [comment]
Hey Timothy!

Could you please confirm that this solved your problem? I want to close the issue if possible. :)

Best,
Christoph
