### ISSUE TITLE
CMake could not find OpenCV 

### ISSUE THREAD

**Issue by tohnperfect** [classner/fertilized-forests#30]
Hi Christoph,

I have tried to install the library with the link to OpenCV by passing `-DOpenCV_DIR=.../anaconda/lib` to `cmake ..` but it still could not find OpenCV.

the error message is as follows,

> CMake Warning at CMakeLists.txt:52 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

>  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

>  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.

Thanks in advance.

Tonh

**Comment by classner** [comment]
CMake is a little beast here. It requires OpenCV to be actually *installed* on the machine, not only downloaded. When installing OpenCV on Linux, it copies required files to a standard location where CMake can find it. Then it should work out of the box. :)

**Comment by classner** [comment]
Ok, so let's tackle this first! :) Did you *install* OpenCV properly or just downloaded. Once it is installed, it should be found and used by CMake immediately!

**Comment by tohnperfect** [comment]
I am using pre-compiled version of anaconda. To my understanding OpenCV is just for feature extraction part, isn't it? If so could I just skip this step, because my main focus is to use hough forest with my engineered feature?

**Comment by classner** [comment]
It is definitely not necessary to pursue your aim. I just thought it might help debugging, but we can do without. So I am closing this issue, since I verified that the build works find if OpenCV is installed.
