### ISSUE TITLE
RuntimeError: unregistered class - derived class not registered or exported

### ISSUE THREAD

**Issue by tohnperfect** [classner/fertilized-forests#32]
Sorry again Christoph. after i managed to trian the classifier I got this error.
> Traceback (most recent call last):
  File "hough_train.py", line 135, in <module>
    pickle.dump(forest, df)
  File "/home/localadmin/anaconda/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/home/localadmin/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/localadmin/anaconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
RuntimeError: unregistered class - derived class not registered or exported

which google said it the problem from boosting.
Any suggested workaround for that?

**Comment by classner** [comment]
I can probably guess what the cause of that is. What kind of 'soil' did you use to create the forest? I'll check what went wrong then.

All classes must be registered so that they can be serialized. Most probably you used an unusual combination of datatypes to create your hough forest, and the objects are not registered to be exported. This should not be possible (so I'll fix it on the master branch), but it is very easy to add the registration for the missing object to make it work.

**Comment by tohnperfect** [comment]
I followed the hough_train.py example, which is `soil = fertilized.Soil('uint8', 'int16', 'int16', fertilized.Result_Types.hough_map).` the only thing I did change is I removed the feature extraction part and pass raw RGB values data to train the forest instead (which I did make each data to be contiguous array with shape = (#Channels, Height, Width).

**Comment by classner** [comment]
Is the plain example then running for you? That sounds unrealistic, because the data you pass through an object does not change its serialization properties...

**Comment by tohnperfect** [comment]
Yes I just tried to learn how to use the package from the plain example without modify anything else.

**Comment by classner** [comment]
Ok, but just for the record: you can run the `hough_train.py` example unmodified and it runs successfully? Please excuse asking that again, but it's important to find the cause for this issue and it will make it much easier... :)

**Comment by tohnperfect** [comment]
No. I couldnot. Because I did not successfully config the package with opencv.

**Comment by classner** [comment]
Investigating further on the issue, I built the library from the master branch without OpenCV, as you stated. I then stripped down the `hough_train.py` example to train on a minimal synthetic sample and it runs completely fine for me. Can you try running this?

```
#%% Imports
from PIL import Image
import skimage.color
import numpy as np
import os
import sys
sys.path.insert(0, os.path.join('..', '..', 'build', 'bindings', 'python'))
if len(sys.argv) > 2:
  print('Quiet mode. Plot display disabled.')
  INTERACTIVE = False
else:
  INTERACTIVE = True
import matplotlib.pyplot as plt
import fertilized
import pickle
from hough_preferences import patch_size, n_trees, min_samples_per_split, \
  max_depth, n_splits, n_thresholds, n_samples_pos, n_samples_neg, \
  n_feature_channels, max_patches_per_node, n_threads, root_dir, image_dir, \
  annot_dir

if len(sys.argv) > 1:
  root_dir = sys.argv[1]

np.random.seed(8)

n_samples_pos = 1
n_samples_neg = 1

#%% Feature extraction.
soil = fertilized.Soil('uint8', 'int16', 'int16', fertilized.Result_Types.hough_map)

feat_images = [np.zeros((13, 50, 50), dtype='uint8'), np.ones((13, 50, 50), dtype='uint8')]
annotations = np.array([[1, 25, 25, 25, 25],
                        [0, 25, 25, 25, 25]], dtype='int16')
n_samples_pos = 1
train_pos_ids = [0]


#%% Forest construction.
random_init = 1
trees = []
for tree_idx in range(n_trees):
  print('Constructing and training tree %d.' % (tree_idx))
  random_seed = tree_idx * 2 + 1 + random_init * n_trees
  sman = soil.NoCopyPatchSampleManager(
            feat_images,
            annotations,
            n_samples_pos * len(train_pos_ids),
            n_feature_channels,
            patch_size[0],
            patch_size[1],
            False)
  dprov = soil.SubsamplingDataProvider(max_patches_per_node,
                                       sman,
                                       random_seed)
  tree = soil.StandardHoughTree((patch_size[1],patch_size[0],n_feature_channels),
                                n_thresholds,
                                n_splits,
                                max_depth,
                                (1, min_samples_per_split),
                                random_seed,
                                (0.,0.),
                                patch_annot_luc=False,
                                allow_redraw=False,
                                num_threads=n_threads,
                                entropy_names=['shannon', 'shannon'])
  tree.fit_dprov(dprov, True)
  trees.append(tree)

#%%
forest = soil.CombineTrees(trees)
with open('forest.pkl', 'w') as df:
  pickle.dump(forest, df)
```

**Comment by tohnperfect** [comment]
I got the same problem as before with the above script.

> Traceback (most recent call last):
  File "hough_train2.py", line 72, in <module>
    pickle.dump(forest, df)
  File "/.../anaconda/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/.../anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/.../anaconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
RuntimeError: unregistered class - derived class not registered or exported

**Comment by classner** [comment]
Can you try using the `forest.save` method instead? Just remove the

```
with open('forest.pkl', 'w') as df:
  pickle.dump(forest, df)
```

part and replace it with `forest.save('test.ff')`.

**Comment by tohnperfect** [comment]
I got this error,

> RuntimeError: unregistered class - derived class not registered or exported

**Comment by classner** [comment]
Ok, so I can not reproduce the error so far. I might need some more information. Just to make sure: when you built the library, did you alter anything before (like the `CMakeLists.txt`) to get it to compile? 

* Did you build it with the serialization features switched on (`-DWITH_SERIALIZATION=On`, is on by default)?
* Which version of Python are you using?
* Did you build from the master branch?
* Which boost version are you using?

It really puzzles me, because on all architectures I get the examples to run, across Linux, Mac and Windows. And usually for the regression tests, I am using the Miniconda distribution as well (minimal Anaconda). But I'll do my best to reproduce this...

**Comment by tohnperfect** [comment]
I built it from the master branch and I did not change `CMakelists.txt`.
I checked in the the `CMakeCache.txt` the WITH_SERIALIZATION:BOOL=ON.
I am using python 2.7.11|Anaconda 1.9.2 (64-bit) and boost version 1.57

**Comment by classner** [comment]
I could reproduce the error with your system specs. It does not occur with the system provided boost (v1.54), but I *think* it's not boost version specific but maybe Anaconda boost specific. On Windows, I used a newer version of boost (1.58), as well as for the CI, and I think it worked all just fine.

If you want to recreate, this is the Dockerfile I used:

```
FROM ubuntu:14.04
# Get build tools.
RUN apt-get -y install apt-utils software-properties-common; add-apt-repository -y ppa:ubuntu-toolchain-r/test; apt-get update -qq; apt-get -y install build-essential g++-4.8
# Install cmake.
RUN apt-get -y install wget
RUN wget --quiet http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.sh; chmod a+x cmake-3.2.3-Linux-x86_64.sh; ./cmake-3.2.3-Linux-x86_64.sh --skip-license --prefix=/usr/local
# Install Anaconda.R
RUN wget -O anaconda.sh --quiet https://repo.continuum.io/archive/Anaconda2-2.5.0-Linux-x86_64.sh; chmod a+x anaconda.sh;
RUN ./anaconda.sh -b
RUN ln -s /root/anaconda2 /root/anaconda
# Install Eigen.
RUN wget --quiet http://bitbucket.org/eigen/eigen/get/3.2.5.tar.gz; tar -xzvf 3.2.5.tar.gz 2>/dev/null;
# Download source.
RUN apt-get -y install git
RUN git clone https://github.com/classner/fertilized-forests.git
RUN apt-get -y install libboost-all-dev
# Setup build.
#RUN /root/anaconda/bin/conda install boost
RUN mkdir fertilized-forests/build; cd fertilized-forests/build; cmake -DWITH_PYTHON=On -DWITH_MATLAB=Off -DWITH_CAFFE=Off -DEIGEN3_INCLUDE_DIR=/eigen-eigen-bdd17ee3b1b3 -DWITH_OPENCV=Off -DPYTHON_EXECUTABLE=/root/anaconda/bin/python -DPYTHON_INCLUDE_DIR=/root/anaconda/include/python2.7 -DPYTHON_LIBRARY=/root/anaconda/lib/libpython2.7.so ..
# Not required for system boost.
# -DBoost_INCLUDE_DIR=/root/anaconda/include -DBoost_LIBRARY_DIR=/root/anaconda/lib ..
# Build.
RUN cd fertilized-forests/build; cmake --build . -- -j6
# Setup example.
COPY github-test.py /fertilized-forests/examples/python/github-test.py
# Install the library.
RUN cd /fertilized-forests/build/bindings/python; /root/anaconda/bin/python setup.py install
# Run the example.
RUN /root/anaconda/bin/python /fertilized-forests/examples/python/github-test.py
```
and the file `github-test.py`:
```
#%% Imports
from PIL import Image
import skimage.color
import numpy as np
import os
import sys
sys.path.insert(0, os.path.join('..', '..', 'build', 'bindings', 'python'))
if len(sys.argv) > 2:
  print('Quiet mode. Plot display disabled.')
  INTERACTIVE = False
else:
  INTERACTIVE = True
import fertilized
import pickle
from hough_preferences import patch_size, n_trees, min_samples_per_split, \
  max_depth, n_splits, n_thresholds, n_samples_pos, n_samples_neg, \
  n_feature_channels, max_patches_per_node, n_threads, root_dir, image_dir, \
  annot_dir

if len(sys.argv) > 1:
  root_dir = sys.argv[1]

np.random.seed(8)

n_samples_pos = 1
n_samples_neg = 1

#%% Feature extraction.
soil = fertilized.Soil('uint8', 'int16', 'int16', fertilized.Result_Types.hough_map)

feat_images = [np.zeros((13, 50, 50), dtype='uint8'), np.ones((13, 50, 50), dtype='uint8')]
annotations = np.array([[1, 25, 25, 25, 25],
                        [0, 25, 25, 25, 25]], dtype='int16')
n_samples_pos = 1
train_pos_ids = [0]


#%% Forest construction.
random_init = 1
trees = []
for tree_idx in range(n_trees):
  print('Constructing and training tree %d.' % (tree_idx))
  random_seed = tree_idx * 2 + 1 + random_init * n_trees
  sman = soil.NoCopyPatchSampleManager(
            feat_images,
            annotations,
            n_samples_pos * len(train_pos_ids),
            n_feature_channels,
            patch_size[0],
            patch_size[1],
            False)
  dprov = soil.SubsamplingDataProvider(max_patches_per_node,
                                       sman,
                                       random_seed)
  tree = soil.StandardHoughTree((patch_size[1],patch_size[0],n_feature_channels),
                                n_thresholds,
                                n_splits,
                                max_depth,
                                (1, min_samples_per_split),
                                random_seed,
                                (0.,0.),
                                patch_annot_luc=False,
                                allow_redraw=False,
                                num_threads=n_threads,
                                entropy_names=['shannon', 'shannon'])
  tree.fit_dprov(dprov, True)
  trees.append(tree)

#%%
forest = soil.CombineTrees(trees)
with open('forest.pkl', 'w') as df:
  pickle.dump(forest, df)
```

Just put the two in an empty directory and run `docker build .`.

To solve your problem, I would just do `apt-get install libboost-all-dev` and start from a fresh build directory. It should then not be necessary to specify a boost include or library directory. There should be no clashes between that boost version and the anaconda python.

Let me know if this helped!

**Comment by tohnperfect** [comment]
I have installed `libboost-all-dev` and downloaded a fresh copy of the package but I still got the same error.

I would try install everything on fresh copy of linux when I have time and will let you know.

Thank you for helping me.

**Comment by classner** [comment]
Before you get a fresh copy of Linux, try removing the Anaconda boost! Maybe this solves the problem already!

Btw., this is a good idea anyways, since there may be other clashes with system boost. Anaconda sidestepping the system package manager is not a good concept. This goes as well for the OpenCV library... I used to be a heavy Anaconda user on Windows, but on Linux it doesn't play that nicely.

**Comment by classner** [comment]
Just to keep up-to-date: did you solve the problem?
