### ISSUE TITLE
KeyError when using generate.py

### ISSUE THREAD

**Issue by kensho-** [classner/fertilized-forests#35]
Hi,

I tried to implement multi-class version of ```HoughLeafManager```.
I made MultiClassHoughLeafManager.h and implemented it.
To store class labels in addition to probability and offsets,
I used ```std::tuple<float, std::shared_ptr<std::vector<annotation_dtype>>, std::shared_ptr<std::vector<annotation_dtype>>>``` as ```leaf_return_dtype```.
I also added Instantiations in ```ileafmanager.h``` as follows
```
* - float; int16_t; std::tuple<float, std::shared_ptr<std::vector<int16_t>>, std::shared_ptr<std::vector<int16_t>>>; std::vector<std::tuple<float, std::shared_ptr<std::vector<int16_t>>, std::shared_ptr<std::vector<int16_t>>>>
```

Then I executed ```python generate.py```.
The following error occured.
```
[started  parsing] ../../include/fertilized\leafs/ileafmanager.h
Traceback (most recent call last):
  File "generate.py", line 24, in <module>
    import ParseHeader
  File "C:\fertilized-forests\fertilized-devtools\binding_generator\ParseHeader.py", line 40, in <module>
    cls, funcs, using_rels = sfp.ParseToIntermediateObject()
  File "C:\fertilized-forests\fertilized-devtools\binding_generator\SingleFileParser.py", line 35, in ParseToIntermediateObject
    intermediateObject = self.ParseClass(cls)
  File "C:\fertilized-forests\fertilized-devtools\binding_generator\SingleFileParser.py", line 105, in ParseClass
    availableIn, types, soilUsage, serialization_generation = dte.Extract()
  File "C:\fertilized-forests\fertilized-devtools\binding_generator\DoxygenTypeExtractor.py", line 106, in Extract
    instantiations.append(InstantiationTypes(result))
  File "C:\fertilized-forests\fertilized-devtools\binding_generator\helper_classes.py", line 289, in __init__
    for type in types])
KeyError: 'std::tuple<float,int,std::shared_ptr<std::vector<int16_t>>>'
```

Source code of MultiClassHoughLeafManager.h is following.
https://github.com/kensho-/fertilized-forests/blob/work/include/fertilized/leafs/multiclasshoughleafmanager.h

Do you have any idea for this problem?

**Comment by classner** [comment]
Hi Kensho!

Thanks for bringing this up, I identified the problem, it is easy to fix. To represent the template internally, short names are required. These are set in the file `TypeTranslations.py` of the `fertilized-devtools`, and the new type you introduced is not registered there. You can simply add it to the `dtype_str_translation` dictionary and this should make things work.

However, the error message was really bad and not hinting at this. I just pushed a patch fixing this, so that a proper error message is displayed with instructions on how to fix the problem.

Let me know if this helped!

Best,
Christoph

**Comment by kensho-** [comment]
Thank you Christoph.
I added new type to ```dtype_str_translation``` and solved the problem!

I have not confirmed whether MultiClassHoughLeafManager works or not yet.
But I could build the library with my new class.

**Comment by classner** [comment]
Ok, good luck with it! If there are further library-related issues coming up, just let me know!
