### ISSUE TITLE
Compilation error Windows 10, MSVC 2013

### ISSUE THREAD

**Issue by tomhaeck** [classner/fertilized-forests#38]
Hey,

I am in the process of compiling the fertilized-forests matser branch.  Dependency versions are:
- CMake 3.5.2
- Boost 1.64.0
- Eigen 3.3.4

Compilation is done with MSVC2013 on a Windows 10, x86 architecture.  This should be more or less the same setup as the setup by which the binary is provided on the website.

I get a compilation error in fertilized-forests-master\include\fertilized/ndarray/ExpressionTraits.h:
_**Missing type specifier - int assumed.  Note: C++ does not support default-int.**_

I get this error for every line in ExpressionTraits.h that defines:
**_typedef boost::mpl::true_ IsScalar;_** 
or
**_typedef boost::mpl::false_ IsScalar;_** 

Any help would be very much appreciated.

Regards,

Tom

**Comment by classner** [comment]
Hi Tom,

this was a problem with newer boost versions because of a restructuring of mpl. I included a missing header in `ExpressionTraits.h`, it should work now!

Best,
Christoph

**Comment by tomhaeck** [comment]
Hey Christoph,

Thanks for the incredibly quick reply.  In the meantime, I was trying to build against Boost 1.58. This compiled fine, but some linker errors popped up concerning some boost serialization identifiers.  I will give Boost 1.64 a new try!

Thanks,

Tom

**Comment by tomhaeck** [comment]
Hey Christoph,

The build against Boost 1.64 works great now!

Thanks a lot,
Tom

**Comment by classner** [comment]
Hi Tom,

that's great to hear! As a sidenote: I just noticed a numerical instability in the implementation of the entropies for regression forests. Whether you run into a problem with this depends on your specific data. It won't produce any wrong results, just the forests may not get as deep as required and you may end up with worse performance. Classification forests are completely untouched of this. I might push an update for this here or in a follow-up project...

Good luck with your project,
Christoph

**Comment by tomhaeck** [comment]
Hey Christoph,

Okay,  thanks for the warning.  I will keep an eye on it and check the forest depths, as I am interested in regression forests as well...

Thanks,
Tom
