### ISSUE TITLE
extract_hough_forest_features runtime error

### ISSUE THREAD

**Issue by tomhaeck** [classner/fertilized-forests#39]
Hey all,

The code snippet below throws a runtime error.  

```
	auto soil = Soil<uint8_t,int16_t,int16_t,Result_Types::hough_map>();

	Vector<std::size_t, 3> shape = makeVector<std::size_t>(100,100,3);
	Array<uint8_t, 3, 3 > testarray = allocate(shape);
	testarray.deep() = 1;
	soil.extract_hough_forest_features(testarray, false);
```
Anybody knows why?  I cannot compile in debug mode, so I have no further clues...

Thanks,

Tom

**Comment by classner** [comment]
Could you locate the exact line that throws the runtime error? Also, what kind of error did you get?

**Comment by tomhaeck** [comment]
The error is thrown by the last line.  I am building in Release mode and the program just crashes.  No further information unfortunately.

**Comment by tomhaeck** [comment]
I have managed to compile in Debug mode.  Error is thrown on the function call in the return statement (line 2973 from soil.h):
```
Array<uint8_t , 3 , 3> extract_hough_forest_features(const fertilized::Array<uint8_t const, 3, 3> & image,const bool & full=0) {
	return fertilized::extract_hough_forest_features(image,full);
};
```
The error is very dubious: "Unhandled exception at 0x00007FFD937C3C58 in hough_test.exe: Microsoft C++ exception: fertilized::Fertilized_Exception at memory location 0x00000061A95FFB58."

Really don't know what is happening...

Tom

**Comment by classner** [comment]
Really strange, I can't reproduce the problem. Works flawlessly for me, also accessing the result works fine.

**Comment by tomhaeck** [comment]
That is strange indeed.
The function call in the return statement is a call to a DLLExport function.  I assume the problem is somewhere over there.  I will keep you updated.

**Comment by tomhaeck** [comment]
Hey Christophe,

The problem has been solved.  Apparently, feature calculation requires a build against OpenCV.  By building the library against OpenCV, the problem was easily solved. 

In feature_extraction.cpp, an exception is thrown when OpenCV is not detected:
`    throw Fertilized_Exception("The library has been built without OpenCV and feature extraction is not available!");`

However, this exception was not thrown in my case.  This might have something to do with the dll-nature of the library?

Nevertheless, I'll close this issue!  Thanks for the quick response again...

Tom

**Comment by classner** [comment]
Hi Tom,
great to hear that you sorted it out. Strange that the Exception was not properly thrown...
