### ISSUE TITLE
demo on human pose?

### ISSUE THREAD

**Issue by Minotaur-CN** [classner/fertilized-forests#41]
Dear all,
 I did not find the demo code on hough forest human pose estimation , as describe on homepage?
could you tell me to to implement the human pose estimation?

**Comment by classner** [comment]
It's possible to use Hough Forests for human pose estimation. You'll have to decide for one of the human pose estimation datasets, download it and preprocess the data appropriately (you can base your code on the Hough Forest demo code with the horse detection). However, I can't go into details with that.

As a sidenote: Hough Forest performance for human pose estimation will be significantly worse than more recent deep learning based models for human pose estimation! You might consider using one of those, e.g., https://github.com/eldar/pose-tensorflow .
