### ISSUE TITLE
Save and access trained model

### ISSUE THREAD

**Issue by rameshjesswani** [classner/fertilized-forests#44]
I have trained my model and want to save it for prediction. Could anyone please help me this? I am using library in C++11. Is there any built-in function that library provides to save and access that trained model? 

This is my sample of code, i am using random forest on Iris data set. 
```
 	int numberOfClasses = 3;
 	int numberOfFeatures = 4;
 	auto soil = Soil<>();
 	auto forest = soil.StandardClassificationForest(numberOfClasses, numberOfFeatures);
 	forest -> fit(training_features, training_classes);

 	// predictions
 	cout<<"testing_features "<< testing_features<<endl;
 	Array<double, 2, 2> predictions = forest -> predict(testing_features);
 	std::cout << "Forest predictions: " << std::endl;
  	std::cout << predictions << std::endl;

```

Any help will be appreciated. Thanks :)

**Comment by anittadevadas** [comment]
hiii
kindly help me with matlab code for feature extraction using hough forest
i tried the code in the website

 soil = Soil('uint8', ...
            'int16', ...
            'int16', ...
            Result_Types.hough_map);
        
    feat_images = {};
    for i=1:length(face)
  feat_images{i} = soil.extract_hough_forest_features(face{i}, True);

these lines in matlab 2018a i is not correct
kindly help
