### ISSUE TITLE
Can not open the website

### ISSUE THREAD

**Issue by Learningm** [classner/fertilized-forests#45]
With 503 response while opening http://www.fertilized-forests.org.

**Comment by classner** [comment]
Hi @Learningm !

The website was hosted not by me but my former university lab and is not administered by me any more. It seems they took it down, so I'll remove any links pointing there. Which link did you see pointing there?

**Comment by Learningm** [comment]
I just input this address, http://www.fertilized-forests.org/ and get a 503 response, another address, https://www.uni-augsburg.de/en/fakultaet/fai/informatik/prof/mmc/fertilized/pages/developers-guide.html/, it can't be translated into English so I don't understand the website content, but a 404 lies on the top of the page.

Hope you can make a new API document and I am interested in this implementation of random forest. Thanks !

**Comment by Learningm** [comment]
> Hi @Learningm !
> 
> The website was hosted not by me but my former university lab and is not administered by me any more. It seems they took it down, so I'll remove any links pointing there. Which link did you see pointing there?

I just input this address, http://www.fertilized-forests.org/ and get a 503 response, another address, https://www.uni-augsburg.de/en/fakultaet/fai/informatik/prof/mmc/fertilized/pages/developers-guide.html/, it can't be translated into English so I don't understand the website content, but a 404 lies on the top of the page.

Hope you can make a new API document and I am interested in this implementation of random forest. Thanks !
